# precipitation plot
SHADE_MIN = 1
SHADE_MAX = 51
SHADE_INTERVAL = 5
COLOR_MAP_NAME = "jet"
CBAR_EXTENTION = "max"
CBAR_UNIT = "[mm/h]"
CBAR_LABEL_SIZE = 8
CBAR_LABEL_LOCATION = 7

# elevation map
ELEVATION_MAX = 4050
ELEVATION_MIN = 150
ELEVATION_INTERVAL = 100
CONTOUR_WIDTH = 0.2
CONTOUR_COLOR = "grey"
is_labled_contour = False
CONTOUR_LABEL_INTERVAL = 500
CONTOUR_LABEL_SIZE = 7

# gridline
GRIDLINE_COLOR = "grey"
GRIDLINE_WIDTH = 0.1

# gif & mp4
GIF_INTERVAL = 10
FPS_RATE = 5.0
