# 描画領域の設定
LON_LEFT, LON_RIGHT = 129.87696, 130.4
LAT_BOTTOM, LAT_TOP = 32.606493, 32.997226
LON_LEFT, LON_RIGHT = 135, 142
LAT_BOTTOM, LAT_TOP = 33, 39

# colorbarの設定
SHADE_MIN = 1
SHADE_MAX = 51
SHADE_INTERVAL = 5
DIVIDE_EVENLY = False
COLOR_MAP_NAME = "jet"
CBAR_EXTENTION = "max"
CBAR_UNIT = "[mm/h]"
CBAR_LABEL_SIZE = 8
CBAR_LABEL_LOCATION = 0


# 標高データの設定
PLOT_ELEVATION = True
ELEVATION_MAX = 2050
ELEVATION_MIN = 150
ELEVATION_INTERVAL = 300
CONTOUR_WIDTH = 0.05
CONTOUR_COLOR = "grey"
PLOT_ELEVATION_LABEL = False
CONTOUR_LABEL_INTERVAL = 300
CONTOUR_LABEL_SIZE = 7
ZOOM_LEVEL = 11


# 緯度経度目盛りの設定
IS_DEG_MIN_FORMAT = True
LON_TICKS_INTERVAL = 1
LAT_TICKS_INTERVAL = 1
PLOT_GRID_LINE = False
GRIDLINE_COLOR = "grey"
GRIDLINE_WIDTH = 0.1

# タイトルのfontsize
TITLE_SIZE = 14
TITLE = "precipitation"

GIF_INTERVAL_TIME = 10
FPS_OF_VIDEO = 5.0
